services:
  api:
    build: .
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=addresses
      - ADMIN_TOKEN=changeme
    ports:
      - "10000:8000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=addresses

volumes:
  mongo_data: